language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_deps"
- "./travis-tool.sh install_r testthat testthatsomemore"
#- "./travis-tool.sh install_github robertzk/stagerunner"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: JK4jiaG/f4QLz5jO0DsshMID3qxOEsr3g5+bk+zJu+b40zYTfBPZuIxdv5q6ImUWD8tM50UmLjWJ2XBodzXUGZNVVwAZgD56xIUcEfDy0wsa2r9LRsVnmqxo5Vq318ypWeCe+dR/6rWaiV97g0DOwg7nrqtrqYI/Fz80lUk8poo=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
